FROM python:3.8
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
# ENV PORT=80

ENV FLASK_ENV production
# ENV FLASK_ENV app

CMD [ "python",  "-m" , "flask", "run", "--host=0.0.0.0"]
# CMD ["python", "app.py"]