
name: Python Package

on:
    push:
      branches: [ master ]


jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Check out code
            uses: actions/checkout@v1   

          - name: Login to Docker Registry
            run: docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
            env:
              DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
           #   DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          - name: Start env
            run: docker-compose up
